import type { CardDefinition } from './types';

/**
 * 24 cards covering costs 1..6 with simple, readable abilities.
 * Power is balanced loosely on Marvel Snap's vanilla curve:
 *   cost 1: 2, cost 2: 3, cost 3: 5, cost 4: 7, cost 5: 8/9, cost 6: 12.
 * Cards with strong abilities are slightly under-statted.
 */
export const CARDS: CardDefinition[] = [
  // ----- Jetons -----
  {
    id: 'asterion-double',
    name: 'Double d’Astérion',
    cost: 1,
    power: 3,
    faction: 'silver',
    flavor: 'Un reflet sans âme.',
  },
  {
    id: 'lost-soul',
    name: 'Âme perdue',
    cost: 1,
    power: 1,
    faction: 'neutral',
    flavor: 'Un écho sans volonté.',
  },
  {
    id: 'black-dragon-double',
    name: 'Double du Dragon Noir',
    cost: 1,
    power: 3,
    faction: 'black',
    flavor: 'Un mirage brutal.',
  },
  {
    id: 'saga-illusion',
    name: 'Illusion de Saga',
    cost: 0,
    power: 0,
    faction: 'gold',
    flavor: 'Un reflet trompeur des Gémeaux.',
  },
  {
    id: 'saga-double',
    name: 'Illusion de Saga',
    cost: 0,
    power: 0,
    faction: 'gold',
    flavor: 'Le masque tombe — un doublon sans substance.',
  },

  // ----- Coût 1 -----
  {
    id: 'kiki',
    name: 'Kiki',
    cost: 1,
    power: 1,
    faction: 'neutral',
    flavor: 'Toujours prêt à aider… à sa façon.',
    ability: {
      kind: 'on-reveal',
      id: 'kiki-next-turn-cosmos',
      text: 'Au révélé : +1 Cosmos au prochain tour.',
    },
  },
  {
    id: 'seiya',
    name: 'Pégase Seiya',
    cost: 1,
    power: 2,
    faction: 'bronze',
    flavor: 'Météores de Pégase !',
    ability: {
      kind: 'ongoing',
      id: 'ongoing-buff-self-per-faction-ally',
      text: 'Continu : +1 par allié Bronze en jeu.',
      params: { amount: 1, faction: 'bronze' },
    },
  },
  {
    id: 'june',
    name: 'June du Caméléon',
    cost: 1,
    power: 0,
    faction: 'bronze',
    flavor: 'Liens invisibles.',
    ability: {
      kind: 'ongoing',
      id: 'ongoing-tick-june-cosmos',
      text: 'À chaque tour : +1 cumulatif par Cosmos allié non utilisé.',
      params: { tick: 'tick-june-cosmos-stack' },
    },
  },
  {
    id: 'hyoga',
    name: 'Cygne Hyoga',
    cost: 3,
    power: 4,
    faction: 'bronze',
    flavor: 'Cercueil de glace.',
    ability: {
      kind: 'on-reveal',
      id: 'silence-random-opposing-enemy',
      text: 'Au révélé : silence un effet continu ennemi de ce lieu.',
    },
  },
  {
    id: 'ban',
    name: 'Lionnet Ban',
    cost: 1,
    power: 2,
    faction: 'bronze',
    flavor: 'Rugissement du Lionnet.',
    ability: {
      kind: 'on-reveal',
      id: 'ban-draw-from-deck',
      text: 'Au révélé : pioche une carte du deck pour la mettre en main.',
    },
  },
  {
    id: 'nachi',
    name: 'Nachi du Loup',
    cost: 1,
    power: 2,
    faction: 'bronze',
    flavor: 'Instinct du chasseur.',
    ability: {
      kind: 'on-reveal',
      id: 'nachi-buff-based-on-winning',
      text: 'Au révélé : +2 si vous gagnez déjà ici, sinon +1.',
    },
  },
  {
    id: 'shun',
    name: 'Andromède Shun',
    cost: 1,
    power: 1,
    faction: 'bronze',
    flavor: 'Chaîne nébulaire.',
    ability: {
      kind: 'ongoing',
      id: 'ongoing-buff-allies-here',
      text: 'Continu : +1 à vos autres alliés ici.',
      params: { amount: 1 },
    },
  },
  {
    id: 'skeleton',
    name: 'Spectre Squelette',
    cost: 1,
    power: 2,
    faction: 'specter',
    flavor: 'Soldat des Enfers.',
  },
  {
    id: 'black-pegasus',
    name: 'Pégase Noir',
    cost: 1,
    power: 2,
    faction: 'black',
    flavor: 'Météores corrompus.',
    ability: {
      kind: 'on-reveal',
      id: 'debuff-random-enemy-here-1',
      text: 'Au révélé : -1 à une carte ennemie aléatoire ici.',
    },
  },
  {
    id: 'black-andromeda',
    name: 'Andromède Noir',
    cost: 1,
    power: 1,
    faction: 'black',
    flavor: 'Chaînes des ténèbres.',
    ability: {
      kind: 'ongoing',
      id: 'ongoing-andromede-noir-per-black',
      text: 'Continu : +1 pour chaque Chevalier Noir en jeu.',
    },
  },
  {
    id: 'black-phoenix',
    name: 'Phénix Noir',
    cost: 1,
    power: 2,
    faction: 'black',
    flavor: 'Cendres impures.',
  },

  // ----- Coût 2 -----
  {
    id: 'jabu',
    name: 'Licorne Jabu',
    cost: 2,
    power: 2,
    faction: 'bronze',
    flavor: 'Charge de la Licorne.',
    ability: {
      kind: 'ongoing',
      id: 'ongoing-bonus-when-full',
      text: 'Continu : +5 si ce lieu est plein de votre côté.',
      params: { amount: 5 },
    },
  },
  {
    id: 'geki',
    name: 'Ours Geki',
    cost: 2,
    power: 2,
    faction: 'bronze',
    flavor: 'Force colossale.',
    ability: {
      kind: 'ongoing',
      id: 'ongoing-no-decrease-self',
      text: 'Continu : sa puissance ne peut pas être diminuée.',
    },
  },
  {
    id: 'black-cygnus',
    name: 'Cygnus Noir',
    cost: 2,
    power: 1,
    faction: 'black',
    flavor: 'Glace volée.',
    ability: {
      kind: 'on-reveal',
      id: 'cygnus-noir-cosmos-then-selfdestruct',
      text: 'Au révélé : +2 Cosmos au prochain tour, puis s’auto-détruit.',
    },
  },
  {
    id: 'ichi',
    name: 'Hydre Ichi',
    cost: 1,
    power: -1,
    faction: 'bronze',
    flavor: 'Traître venimeux.',
    ability: {
      kind: 'on-reveal',
      id: 'ichi-switch-enemy-side',
      text: 'Au révélé : passe du côté adverse sur ce lieu.',
    },
  },
  {
    id: 'shiryu',
    name: 'Dragon Shiryu',
    cost: 1,
    power: 1,
    faction: 'bronze',
    flavor: 'Colère du Dragon !',
    ability: {
      kind: 'on-destroy',
      id: 'shiryu-death-buff-allies',
      text: 'À la destruction : +1 permanent aux cartes alliées en jeu. Le dragon s’élève en comète.',
      params: { amount: 1 },
    },
  },
  {
    id: 'ikki',
    name: 'Phénix Ikki',
    cost: 2,
    power: 3,
    faction: 'bronze',
    flavor: 'Renaît de ses cendres.',
    ability: {
      kind: 'on-reveal',
      id: 'phoenix-sacrifice-bounce',
      text: 'Au révélé (1×) : détruit votre allié le plus faible ici, gagne sa puissance, puis retourne en main.',
      params: { oncePerGame: 1 },
    },
  },
  {
    id: 'triton',
    name: 'Marina du Triton',
    cost: 2,
    power: 3,
    faction: 'marina',
    flavor: 'Au service de Poséidon.',
  },
  {
    id: 'dio',
    name: 'Dio de la Mouche',
    cost: 2,
    power: 2,
    faction: 'silver',
    flavor: 'Rapide et insaisissable.',
  },
  {
    id: 'jamian',
    name: 'Jamian du Corbeau',
    cost: 1,
    power: 1,
    faction: 'silver',
    flavor: 'Messager des cieux.',
    ability: {
      kind: 'end-reveal',
      id: 'jamian-bounce-plus-one',
      text: 'Fin de révélation : retourne en main avec +1 pwr (sauf dernier tour, reste ici).',
    },
  },
  {
    id: 'silver-saint',
    name: 'Saint d\u2019Argent',
    cost: 2,
    power: 2,
    faction: 'silver',
    flavor: 'Garde des constellations mineures.',
    // carte supprimée du pool : on la garde définie pour éviter de casser
    // d’anciennes parties / uids, mais elle n’est plus dans les decks (voir engine).
    ability: undefined,
  },
  {
    id: 'capella',
    name: 'Capella d’Auriga',
    cost: 2,
    power: 2,
    faction: 'silver',
    flavor: 'Disques mortels.',
    ability: {
      kind: 'on-reveal',
      id: 'capella-destroy-allies-buff',
      text: 'Au révélé : détruit vos autres alliés ici. +2 par carte détruite.',
      params: { perDestroy: 2 },
    },
  },

  // ----- Coût 3 -----
  {
    id: 'aiolia',
    name: 'Aiolia du Lion',
    cost: 3,
    power: 5,
    faction: 'gold',
    flavor: 'Plasma Foudroyant.',
    ability: {
      kind: 'on-reveal',
      id: 'destroy-all-le4-here-except-self',
      text: 'Au révélé : détruit toutes les cartes (alliées et ennemies) ici de puissance < 4 (sauf lui-même).',
      params: { maxPower: 3 },
    },
  },
  {
    id: 'aldebaran',
    name: 'Aldébaran du Taureau',
    cost: 3,
    power: 7,
    faction: 'gold',
    flavor: 'Grande Corne.',
    ability: {
      kind: 'ongoing',
      id: 'ongoing-immune',
      text: 'Continu : indestructible. Ne peut pas être détruit, déplacé, renvoyé en main ou dans le deck. Sa puissance ne peut pas être diminuée.',
    },
  },
  {
    id: 'grand-pope',
    name: 'Grand Pope Shion',
    cost: 3,
    power: 3,
    faction: 'gold',
    flavor: 'Le Sanctuaire retient son souffle.',
    ability: {
      kind: 'on-reveal',
      id: 'grand-pope-other-dimension',
      text: 'Au révélé : transforme ce lieu en une autre dimension (plus d\u2019effet de lieu) ; la partie dure 7 tours.',
    },
  },
  {
    id: 'milo',
    name: 'Milo du Scorpion',
    cost: 4,
    power: 5,
    faction: 'gold',
    flavor: 'Aiguille Écarlate.',
    ability: {
      kind: 'ongoing',
      id: 'ongoing-increase-enemy-hand-cost',
      text: 'Continu : les cartes dans la main de l\u2019adversaire coûtent toutes +1.',
      params: { amount: 1 },
    },
  },
  {
    id: 'camus',
    name: 'Camus du Verseau',
    cost: 3,
    power: 3,
    faction: 'gold',
    flavor: 'Cercueil glacé absolu.',
    ability: {
      kind: 'ongoing',
      id: 'ongoing-silence-lane',
      text: 'Continu : les autres effets continus n\u2019agissent pas ici.',
    },
  },
  {
    id: 'black-dragon',
    name: 'Dragon Noir',
    cost: 2,
    power: 2,
    faction: 'black',
    flavor: 'Ombre du Dragon.',
    ability: {
      kind: 'on-reveal',
      id: 'black-dragon-summon-double',
      text: 'Au révélé : ajoute un double (sans effet) sur votre côté ici.',
      params: { tokenId: 'black-dragon-double' },
    },
  },
  {
    id: 'mermaid',
    name: 'Sirène Sorrento',
    cost: 3,
    power: 5,
    faction: 'marina',
    flavor: 'Symphonie funèbre.',
  },
  {
    id: 'sirius',
    name: 'Sirius du Grand Chien',
    cost: 3,
    power: 5,
    faction: 'silver',
    flavor: 'Croc du Grand Chien.',
  },
  {
    id: 'babel',
    name: 'Babel du Centaure',
    cost: 3,
    power: 4,
    faction: 'silver',
    flavor: 'Charge et fracas.',
    ability: {
      kind: 'on-reveal',
      id: 'destroy-enemy-cost-1-or-2-here',
      text: 'Au révélé : détruit un ennemi ici de coût 1 ou 2.',
    },
  },
  {
    id: 'dante',
    name: 'Dante du Cerbère',
    cost: 3,
    power: 3,
    faction: 'silver',
    flavor: 'Chaîne tournoyante.',
    ability: {
      kind: 'on-reveal',
      id: 'dante-destroy-cost-1-all-lanes',
      text: 'Au révélé : détruit toutes les cartes de coût 1 (alliés et ennemis) sur tous les lieux.',
    },
  },
  {
    id: 'moses',
    name: 'Moses de la Baleine',
    cost: 3,
    power: 3,
    faction: 'silver',
    flavor: 'Le poids des marées.',
    ability: {
      kind: 'on-reveal',
      id: 'moses-buff-if-ally-died',
      text: 'Au révélé : si un allié a été détruit, +2 à Moses.',
      params: { amount: 2 },
    },
  },
  {
    id: 'algol',
    name: 'Algol de Persée',
    cost: 3,
    power: 2,
    faction: 'silver',
    flavor: 'Le regard pétrifiant.',
    ability: {
      kind: 'ongoing',
      id: 'ongoing-disable-onreveal-here',
      text: 'Continu : les cartes jouées ici ne déclenchent pas leur effet Au révélé.',
    },
  },
  {
    id: 'misty',
    name: 'Misty du Lézard',
    cost: 3,
    power: 2,
    faction: 'silver',
    flavor: 'Illusions et miroirs.',
    ability: {
      kind: 'ongoing',
      id: 'ongoing-no-decrease-allies',
      text: 'Continu : vos alliés ne peuvent pas être diminués en puissance.',
    },
  },
  {
    id: 'asterion',
    name: 'Astérion (Chiens de Chasse)',
    cost: 2,
    power: 3,
    faction: 'silver',
    flavor: 'Griffes jumelles.',
    ability: {
      kind: 'on-reveal',
      id: 'asterion-create-double',
      text: 'Au révélé : remplit ce lieu de doubles d’Astérion (sans effet).',
    },
  },

  // ----- Coût 4 -----
  {
    id: 'mu',
    name: 'Mû du Bélier',
    cost: 4,
    power: 4,
    faction: 'gold',
    flavor: 'Réparateur d\u2019armures, le mur de cristal.',
    ability: {
      kind: 'ongoing',
      id: 'ongoing-protect-allies-here',
      text: 'Continu : aucune carte ici ne peut être détruite.',
    },
  },
  {
    id: 'aiolos',
    name: 'Aiolos du Sagittaire',
    cost: 5,
    power: 5,
    faction: 'gold',
    flavor: 'Le héros véritable.',
    ability: {
      kind: 'on-reveal',
      id: 'destroy-strongest-enemy-here',
      text: 'Au révélé : détruit la carte ennemie la plus forte ici.',
    },
  },
  {
    id: 'shaka',
    name: 'Shaka de la Vierge',
    cost: 5,
    power: 4,
    faction: 'gold',
    flavor: 'L\u2019homme le plus proche des dieux.',
    ability: {
      kind: 'ongoing',
      id: 'ongoing-reduce-cost-hand-deck',
      text: 'Continu : réduit le coût de votre main et deck de 1.',
    },
  },
  {
    id: 'aphrodite',
    name: 'Aphrodite des Poissons',
    cost: 4,
    power: 3,
    faction: 'gold',
    flavor: 'Roses démoniaques.',
    ability: {
      kind: 'ongoing',
      id: 'ongoing-debuff-enemies-here',
      text: 'Continu : −1 à toutes les cartes sur ce lieu.',
      params: { amount: 1 },
    },
  },
  {
    id: 'siegfried',
    name: 'Siegfried (Asgard)',
    cost: 4,
    power: 7,
    faction: 'asgard',
    flavor: 'Dragon Nibelung.',
  },
  {
    id: 'shaina',
    name: 'Shaina d’Ophiuchus',
    cost: 4,
    power: 3,
    faction: 'silver',
    flavor: 'Masque et poison.',
    ability: {
      kind: 'on-reveal',
      id: 'shaina-buff-silver-allies',
      text: 'Au révélé : +1 à chaque Chevalier d’Argent allié en jeu.',
      params: { amount: 1, faction: 'silver' },
    },
  },
  {
    id: 'marine',
    name: 'Marine de l’Aigle',
    cost: 2,
    power: 2,
    faction: 'silver',
    flavor: 'Maîtresse au cœur d’or.',
    ability: {
      kind: 'on-reveal',
      id: 'marine-neutralize-location',
      text: 'Au révélé : transforme ce lieu en zone sans effet.',
    },
  },
  {
    id: 'ptolemy',
    name: 'Ptolemy de la Flèche',
    cost: 3,
    power: 3,
    faction: 'silver',
    flavor: 'Trait implacable.',
    ability: {
      kind: 'on-reveal',
      id: 'debuff-weakest-enemy-here-3',
      text: 'Au révélé : -3 à l’ennemi le plus faible ici.',
    },
  },
  {
    id: 'algethi',
    name: 'Algethi d’Hercule',
    cost: 4,
    power: 6,
    faction: 'silver',
    flavor: 'Force brute.',
  },
  {
    id: 'daidalos',
    name: 'Daidalos de Céphée',
    cost: 3,
    power: 2,
    faction: 'silver',
    flavor: 'Maître des enseignements.',
    ability: {
      kind: 'ongoing',
      id: 'ongoing-plus-per-ally-without-ability',
      text: 'Continu : donne +2 aux alliés sans effet.',
      params: { amount: 2 },
    },
  },

  // ----- Coût 5 -----
  {
    id: 'saga',
    name: 'Saga des Gémeaux',
    cost: 5,
    power: 8,
    faction: 'gold',
    flavor: 'Les deux visages du Grand Pope.',
    ability: {
      kind: 'on-reveal',
      id: 'saga-create-illusion',
      text: 'Au révélé : crée une Illusion de Saga (0 Puissance) dans un autre lieu. L’adversaire ne sait plus où se trouve le vrai Saga.',
    },
  },
  {
    id: 'deathmask',
    name: 'DeathMask du Cancer',
    cost: 3,
    power: 3,
    faction: 'gold',
    flavor: 'Les visages hurlants…',
    ability: {
      kind: 'on-reveal',
      id: 'deathmask-add-lost-souls',
      text: 'Au révélé : invoque une Âme perdue (1) sur chaque autre lieu, des deux côtés.',
    },
  },
  {
    id: 'dokko',
    name: 'Dohko de la Balance',
    cost: 5,
    power: 0,
    faction: 'gold',
    flavor: 'Les armes de la Balance.',
    ability: {
      kind: 'ongoing',
      id: 'ongoing-double-allies-here',
      text: 'Continu : multiplie par 2 la puissance des alliés sur ce lieu.',
    },
  },
  {
    id: 'roshi',
    name: 'Vieux Maître Roshi',
    cost: 5,
    power: 4,
    faction: 'neutral',
    flavor: 'L’entraînement du Sanctuaire.',
    ability: {
      kind: 'on-reveal',
      id: 'reveal-buff-allied-knights',
      text: 'Au révélé : +1 à tous les Chevaliers de Bronze, d’Argent et d’Or alliés.',
      params: { amount: 1 },
    },
  },
  {
    id: 'shura',
    name: 'Shura du Capricorne',
    cost: 4,
    power: 8,
    faction: 'gold',
    flavor: 'Excalibur.',
    ability: {
      kind: 'on-reveal',
      id: 'shura-reveal-and-destroy',
      text: 'Au révélé : invoque une carte du deck adverse de son côté ici ; elle se révèle et joue son effet. Détruit-la ensuite si sa puissance est inférieure et qu\u2019elle n\u2019est pas indestructible.',
    },
  },
  // (mis de côté) Shion du Bélier
  {
    id: 'hilda',
    name: 'Hilda de Polaris',
    cost: 5,
    power: 8,
    faction: 'asgard',
    flavor: 'Représentante d\u2019Odin.',
    ability: {
      kind: 'ongoing',
      id: 'ongoing-buff-allies-here',
      text: 'Continu : +1 à vos autres alliés ici.',
      params: { amount: 1 },
    },
  },
  {
    id: 'kanon',
    name: 'Kanon du Dragon des Mers',
    cost: 5,
    power: 9,
    faction: 'marina',
    flavor: 'Frère oublié de Saga.',
  },
  {
    id: 'orphee',
    name: 'Orphée de la Lyre',
    cost: 5,
    power: 5,
    faction: 'silver',
    flavor: 'Mélodie fatale.',
    ability: {
      kind: 'on-reveal',
      id: 'orphee-bounce-enemy-if-losing',
      text: 'Au révélé : si vous perdez ce lieu, renvoie un ennemi d’ici en main.',
    },
  },

  // ----- Coût 6 -----
  // (mis de côté) Hadès
  // (mis de côté) Poséidon
  {
    id: 'athena',
    name: 'Athéna',
    cost: 6,
    power: 8,
    faction: 'god',
    flavor: 'Déesse de la sagesse, protectrice du Sanctuaire.',
    ability: {
      kind: 'ongoing',
      id: 'ongoing-global-buff',
      text: 'Continu : +1 à vos autres alliés partout.',
      params: { amount: 1 },
    },
  },
  {
    id: 'grand-pope-ares',
    name: 'Grand Pope Arès',
    cost: 6,
    power: 0,
    faction: 'god',
    flavor: 'La colère divine consume les âmes tombées.',
    ability: {
      kind: 'ongoing',
      id: 'ongoing-power-equals-destroyed-total',
      text: 'Continu : sa puissance égale la somme des puissances des cartes détruites dans la partie.',
    },
  },
  // (mis de côté) Thanatos
];

/** Jetons / doublons invoqués en jeu — non sélectionnables dans un deck. */
export const TOKEN_CARD_IDS = new Set([
  'asterion-double',
  'lost-soul',
  'black-dragon-double',
  'saga-illusion',
  'saga-double',
]);

export function isTokenCard(defId: string): boolean {
  return TOKEN_CARD_IDS.has(defId);
}

const CARD_BY_ID: Record<string, CardDefinition> = Object.fromEntries(
  CARDS.map((c) => [c.id, c]),
);

export function getCardDef(id: string): CardDefinition {
  const def = CARD_BY_ID[id];
  if (!def) throw new Error(`Unknown card id: ${id}`);
  return def;
}
